[theme]
primaryColor = "#04b488"
backgroundColor = "#060809"
secondaryBackgroundColor = "#1e2224"
textColor = "#f2f5f7"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
